### ISSUE TITLE
您好，请问checkpoints怎么获取呢？

### ISSUE THREAD

**Issue by Sunting78** [ZZZHANG-jx/GCDRNet#1]

**Comment by ZZZHANG-jx** [comment]
这里可以下载： https://1drv.ms/f/s!Ak15mSdV3Wy4iYkeUK0TYUAajBPaBQ?e=BzXbk3

**Comment by rxmao** [comment]
> 这里可以下载： https://1drv.ms/f/s!Ak15mSdV3Wy4iYkeUK0TYUAajBPaBQ?e=BzXbk3

貌似链接打不开

**Comment by ZZZHANG-jx** [comment]
> > 这里可以下载： https://1drv.ms/f/s!Ak15mSdV3Wy4iYkeUK0TYUAajBPaBQ?e=BzXbk3
> 
> 貌似链接打不开

上传了一份百度云

链接：https://pan.baidu.com/s/14dC3KpOVLOSS94Nf2M0VDg?pwd=2qqu 
提取码：2qqu
