### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by foocker** [ZZZHANG-jx/GCDRNet#4]
DocRes中有训练数据的制作方式，但是代码上似乎存在含糊的地方。 illumination/doc3dshadow/new_shadow 这个目录下的数据，长啥样？ 使用shadow_extraction.py从img.zip （来自Doc3DShade的三个压缩文件中的一个）中提取的阴影似乎并对？data/MBD/infer.py dewarp 得到的shadow img 。。

哦哦，写到这里，我好像懂了， 
在task == 'appearance'：
提取的shadow img 是对未展平的文档做了内容去除，然后 dewarp 得到，近似展平的无内容，但包含了背景色的，同时有阴影的图，这个图作为阴影图集，在训练appearence的时候，从中随机抽取一张，和某干净文档据(gt)，其会先和其他数据的gt做背景融合(bleed_trough)得到cap_im， 然后在把阴影作用cap_im上？

**Comment by ZZZHANG-jx** [comment]
> DocRes中有训练数据的制作方式，但是代码上似乎存在含糊的地方。 illumination/doc3dshadow/new_shadow 这个目录下的数据，长啥样？ 使用shadow_extraction.py从img.zip （来自Doc3DShade的三个压缩文件中的一个）中提取的阴影似乎并对？data/MBD/infer.py dewarp 得到的shadow img 。。
> 
> 哦哦，写到这里，我好像懂了， 在task == 'appearance'： 提取的shadow img 是对未展平的文档做了内容去除，然后 dewarp 得到，近似展平的无内容，但包含了背景色的，同时有阴影的图，这个图作为阴影图集，在训练appearence的时候，从中随机抽取一张，和某干净文档据(gt)，其会先和其他数据的gt做背景融合(bleed_trough)得到cap_im， 然后在把阴影作用cap_im上？

shadow_extraction.py旨在从原图中提取出阴影图；data/MBD/infer.py是一个基于mask的矫正脚本，旨在去除文档的背景。依次使用shadow_extraction.py和data/MBD/infer.py得到的结果分别如下图2和3所示。我们最终使用的是图3的结果，将其作用在pdf图像上来合成数据。
图1：
![图1](https://github.com/user-attachments/assets/de3de189-79c3-47b1-8358-2f43cd189767)
图2：
![图2](https://github.com/user-attachments/assets/ec555d69-3feb-4244-add6-406c2fcfd229)
图3：
![图3](https://github.com/user-attachments/assets/940280e0-13ed-4e76-8394-7614fe78f666)

**Comment by foocker** [comment]
> > DocRes中有训练数据的制作方式，但是代码上似乎存在含糊的地方。 illumination/doc3dshadow/new_shadow 这个目录下的数据，长啥样？ 使用shadow_extraction.py从img.zip （来自Doc3DShade的三个压缩文件中的一个）中提取的阴影似乎并对？data/MBD/infer.py dewarp 得到的shadow img 。。
> > 哦哦，写到这里，我好像懂了， 在task == 'appearance'： 提取的shadow img 是对未展平的文档做了内容去除，然后 dewarp 得到，近似展平的无内容，但包含了背景色的，同时有阴影的图，这个图作为阴影图集，在训练appearence的时候，从中随机抽取一张，和某干净文档据(gt)，其会先和其他数据的gt做背景融合(bleed_trough)得到cap_im， 然后在把阴影作用cap_im上？
> 
> shadow_extraction.py旨在从原图中提取出阴影图；data/MBD/infer.py是一个基于mask的矫正脚本，旨在去除文档的背景。依次使用shadow_extraction.py和data/MBD/infer.py得到的结果分别如下图2和3所示。我们最终使用的是图3的结果，将其作用在pdf图像上来合成数据。 图1： ![图1](https://private-user-images.githubusercontent.com/49354655/367307798-de3de189-79c3-47b1-8358-2f43cd189767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzgwMTAsIm5iZiI6MTcyNjI3NzcxMCwicGF0aCI6Ii80OTM1NDY1NS8zNjczMDc3OTgtZGUzZGUxODktNzljMy00N2IxLTgzNTgtMmY0M2NkMTg5NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmI2MTllZTAwMWZkMTA3OTlmYjNmMjAwZTc4MGU3N2EwZWVkOGMyMjZhMmI5ZDY1YjUwY2MxMjU2ODI5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ibCbyI2FPvKO6Uo3336Da4lBUX1d2MpAYCoGYxCwKx0) 图2： ![图2](https://private-user-images.githubusercontent.com/49354655/367307888-ec555d69-3feb-4244-add6-406c2fcfd229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzgwMTAsIm5iZiI6MTcyNjI3NzcxMCwicGF0aCI6Ii80OTM1NDY1NS8zNjczMDc4ODgtZWM1NTVkNjktM2ZlYi00MjQ0LWFkZDYtNDA2YzJmY2ZkMjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjliNTg3ZGJlZDFjMzNlYzQxNDZjMDI4NGRmOGMwZWRlM2Y2MTg3ODZkNDBiNzUxMjNlYmVmM2U2YjRkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IpYCsTYnRTlzO0IiPhlrKRnI5Sc0Edpptr5VXY5mgp4) 图3： ![图3](https://private-user-images.githubusercontent.com/49354655/367307921-940280e0-13ed-4e76-8394-7614fe78f666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzgwMTAsIm5iZiI6MTcyNjI3NzcxMCwicGF0aCI6Ii80OTM1NDY1NS8zNjczMDc5MjEtOTQwMjgwZTAtMTNlZC00ZTc2LTgzOTQtNzYxNGZlNzhmNjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTM1MDUxMmIyZTM0YTQ2ZDBmZTVjNDhlOTY4Y2FhMTk0NTdmZWQyYjA3NDJiMTI0Y2Q4ZDY5Y2NhOTIyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Jzlvj1hgvD7KDIZjT9nzi-DiB9rmA3mnZmA_ehiFUA)

ok。不过我测试了下，这里的dewarp效果很一般。对这种纯背景的阴影'模板'，倒是无所谓。 
我有一个关于appearance 的背景元素过杀问题，appearance 的训练数据的gt基本是背景色是白色的，但是同样会存在有颜色的元素，这个在RealDAE里面是有这样的训练集的，但是，在docres_loader.py中，bleed_trough会从其他图像中提取一些背景元素作为透明图层合并到gt上，函数中的alpha，参数0.75-!,当减小0.75会强化透明元素的去除，但是，同时会强化背景元素的过杀，当增加的话，对导致透明背景或者水印之类的东西去除能力减弱。
哦，我写到这里，觉得就直接增加吧，但，同时，还有一种方案，bleed_trough的其他图集合，应该做个筛选，这个集合只选包含纯色背景的或者噪声图提取的背景，来bleed_trough。这个时候，alpha是多少，其实无所谓了。
